### ISSUE TITLE
   model:get(1).gradInput = nil why this is okay?

### ISSUE THREAD

**Issue by spk921** [facebook/fb.resnet.torch#102]
I had run with resNet model with other script but I had error because of 
https://github.com/facebook/fb.resnet.torch/blob/master/models/resnet.lua#L202 
THis. How come it can do accGradUpdate without gradInput ? 
So doing '   model:get(1).gradInput = nil' is correct?

**Comment by colesbury** [comment]
The `gradInput` of the first module is not used for training since nothing comes before it. cudnn.SpatialConvolution skips updateGradInput if gradInput is nil. See [SpatialConvolution.lua#L390](https://github.com/soumith/cudnn.torch/blob/master/SpatialConvolution.lua#L390)

Note that gradWeight is still computed for the first module.

**Comment by spk921** [comment]
Yes but if you are not using cuda then you will get error.
