### ISSUE TITLE
What is deterministic convolution implementation?

### ISSUE THREAD

**Issue by AlecWong** [facebook/fb.resnet.torch#119]
``` lua
-- Set the CUDNN flags
if opt.cudnn == 'fastest' then
    cudnn.fastest = true
    cudnn.benchmark = true
elseif opt.cudnn == 'deterministic' then
   -- Use a deterministic convolution implementation
   model:apply(function(m)
      if m.setMode then m:setMode(1, 1, 1) end
   end)
end
```

Hi,  codes in model/init.lua. What's the difference between `fastest` and  `deterministic`.

**Comment by colesbury** [comment]
By default cuDNN can choose algorithms for computing the gradInput and gradWeight which are not deterministic: If you run it multiple times you might get slightly different results for the same input/loss.

In general, this isn't a problem, but sometimes it's useful to have results that are bitwise reproducible when you're checking if a change is correct. That's why there is the "deterministic" option.
