### ISSUE TITLE
scale size

### ISSUE THREAD

**Issue by ffmpbgrnn** [facebook/fb.resnet.torch#31]
Hi, thank you so much for sharing the models! I noticed a note in https://github.com/facebook/fb.resnet.torch/tree/master/pretrained#notes said

```
This is on a test crop of size 224x224. On a test crop of size 320x320, the error rate is 20.1/4.8.
```
Do you mean rescale to 320x320 and then crop to 224x224?

**Comment by colesbury** [comment]
By test crop of 320x320 I mean that the image is resized so that the smallest side is 320 pixels, and then cropped to **320x320**. It's evaluated as a fully convolutional network (the fully connected layer is replaced by the equivalent 1x1 convolution).

I've included the note because this is the way ResNet-200 is evaluated in http://arxiv.org/abs/1603.05027.

**Comment by ffmpbgrnn** [comment]
I got it! Thank you for the clarification!
