### ISSUE TITLE
resume error

### ISSUE THREAD

**Issue by BrettLL** [facebook/fb.resnet.torch#34]
when I want to resume my model, It happens the error that 'cannot open <optimState_64.t7> in mode r at /home/tools/torch/pkg/torch/lib/TH/THDiskFile.c:649'.  what should I do to solve this problem,thanks~~

**Comment by BrettLL** [comment]
error is ‘”cannot open ’optimState_64.t7‘ in mode r at /home/tools/torch/pkg/torch/lib/TH/THDiskFile.c:649“

**Comment by colesbury** [comment]
Is there a file in your `-resume <path>` called optimState_64.t7?

**Comment by BrettLL** [comment]
Sure, It is not the problem that it  has no this file, but  can not open in model r.

**Comment by colesbury** [comment]
That's the error message when the file does not exist. Mode "r" just means
open it read-only

**Comment by BrettLL** [comment]
yeah, Thank you. I have checked my files several times. But the problem still exsits. Thanks all the same~

**Comment by BrettLL** [comment]
When I resume the model, the top1,top5 value is always zero. Is it normal??

**Comment by colesbury** [comment]
No, that doesn't sound normal

**Comment by Cysu** [comment]
I think the problem might be caused by [this line](https://github.com/facebook/fb.resnet.torch/blob/master/main.lua#L28) of code. The `opt.resume` should be concatenated before the file path. Or actually it is unnecessary to load the optimState again as it has been done in [checkpoint.latest()](https://github.com/facebook/fb.resnet.torch/blob/master/checkpoints.lua#L24).

**Comment by colesbury** [comment]
Thanks @Cysu !
