### ISSUE TITLE
Sizings, questions, possible error in preresnet

### ISSUE THREAD

**Issue by karpathy** [facebook/fb.resnet.torch#36]
Hi, first thank you very much for maintaining this excellent repo. I had a few questions:

- The sizing patterns are all wrong and suspicious, though I think this is inherited from the ResNet paper. If the input is `224x224` then 7x7 conv with stride 2 pad 3 does not "work out". Does this effectively chop off one pixel from one side? This results in `112x112` maps that then undergo 3x3 pool stride 2, which again does not work out. In this case I assume the pool implementation effectively adds a padding of 1 of zeros? Any comments on these asymmetries and if they are a problem?
- The new [preresnet](https://github.com/facebook/fb.resnet.torch/blob/master/models/preresnet.lua) appears to ignore the new `type` variable. Shouldn't the declaration of `layer` read `layer(block, features, count, stride, type)` with the added `type`, which should then be passed along to children blocks? It's also a little more subtle because you only want `'first'` to apply on the very first block of very first layer, so the `layer` function has to be careful to only pass it in when `i==1`.
- May I ask what the purpose of the additional `model:add(nn.Copy(nil, nil, true))` is on [L132](https://github.com/facebook/fb.resnet.torch/blob/master/models/preresnet.lua#L132)?

**Comment by colesbury** [comment]
- The 7x7 convolution is zero-padded by 3 on each side, so a total padding of 6 on the width and 6 on the height. The max pooling is also padded (by 1 on each side). I think max pooling is padded with -inf instead of zero. The [Torch documentation](https://github.com/torch/nn/blob/master/doc/convolution.md#spatialconvolution) makes it sound like a total padding of 3, but I don't think that's how it's implemented.  (@soumith, is this correct?) 

- Yes, this is a bug -- thanks for catching it. Because of this, the ResNet-200 model has an extra batch norm & ReLU in the first layer, which it shouldn't.

- The extra copy is to make the [`-shareGradInput`](https://github.com/facebook/fb.resnet.torch/blob/master/models/init.lua#L42-L60) option work correctly with this model.  This option re-uses the CUDA storages for `gradInput` when computing the backward pass to save memory, but the implementation is a fragile hack.

**Comment by soumith** [comment]
yes it's symmetric padding, 3 on each side.

**Comment by anibali** [comment]
@colesbury Why is there no `nn.Copy` for cifar10?

**Comment by colesbury** [comment]
@anibali, there should probably be a copy there too in case you run with `-shareGradInput`

**Comment by anibali** [comment]
Great, thanks. Just trying to figure out how everything works :)
