### ISSUE TITLE
Bias variable.

### ISSUE THREAD

**Issue by omkarparkhi** [facebook/fb.resnet.torch#59]
Convolution modules in the pertained models available on the webpage seem to have
bias variable present in them but the same model trained using the code on imagenet 
doesn't seem to have the bias term present. model.module[1].bias is nil for these newly
trained models. Am I missing some steps in training/model configuration?

**Comment by colesbury** [comment]
The models train without a bias since any change in the bias variable would be removed by the subsequent SpatialBatchNormalization during training. This makes training slightly faster.

I added zero-valued bias tensors back to the pre-trained models for better backwards compatibility, since at the time of release, cudnn.torch had only added support for nil biases recently.

**Comment by omkarparkhi** [comment]
I see. Thanks Sam.
