### ISSUE TITLE
Two enqueue in loop

### ISSUE THREAD

**Issue by lichengunc** [facebook/fb.resnet.torch#65]
I was wondering why there two "enqueue" in the "loop"? 
I tested it without the second one, seems still working and speed not slowing down.
![screen shot 2016-06-22 at 11 54 02 am](https://cloud.githubusercontent.com/assets/12834517/16279588/78754db6-3870-11e6-833c-9971beb36088.png)

**Comment by colesbury** [comment]
Basically, we want to keep the thread pool queue full so that data loading is less likely to be a bottleneck.

- The first `enqueue()` adds jobs until the thread pool is full. 
- The `threads:dojob()` waits until one job is complete and pulls it off the end-job queue
- At this point, since the dojob() is blocking, the thread pool may not be full any more. We call `enqueue()` again to add jobs until it's full

**Comment by lichengunc** [comment]
Oh, I see. It is now clear to me! :-)
Thanks.

**Comment by lichengunc** [comment]
Just another question, you mentioned that dojob() is blocking (meanwhile the main program is fetching batches for forward-backward), will the second enqueue() still work simultaneously? 
Isn't this loop running sequentially?

**Comment by colesbury** [comment]
I don't understand your question. The `loop()` code is run sequentially in the main thread. If you run with enough data loading threads, then `dojob()` won't have to wait, which is why you didn't see a slowdown if you remove the second `enqueue()`

**Comment by lichengunc** [comment]
Okay, got it! Thanks.
