### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [facebook/fb.resnet.torch#86]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _torch_, deleted their software history.

https://github.com/facebook/fb.resnet.torch/commit/6f9402dc0433dbd75cf6fb5ad7934d70b32b665b

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask torch developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by colesbury** [comment]
This isn't the torch project. Torch is at github.com/torch/torch7

I squashed the git history continuously before release because I thought it made the project cleaner. Otherwise, the git history would largely consist of edits to the README files. Something in-between complete squashing and no squashing  of commits would have required more effort.

The git history also would not have captured the actual evolution of the software, which includes Soumith's [imagenet training scripts](https://github.com/soumith/imagenet-multiGPU.torch), internal training scripts, and [Torchnet](https://github.com/torchnet/torchnet).

I'm not aware of any problems related to the lack of git history before the release.

**Comment by gustavopinto** [comment]
Hi @colesbury, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
