### ISSUE TITLE
Data value

### ISSUE THREAD

**Issue by albicasty** [facebook/fb.resnet.torch#94]
Hi!
I am curious about a value displayed during the training phase, the Data. In my modified ResNet this value is always around 0.001, while in the classical implementation is around the Time value. I saw in the code that the Data value is the timer value starting at each epoch. My question is more about how it can be such big value, because at the end of each iteration (epoch) the timer is set to 0, right away in the new cycle Data is set to the value of the timer. Here attached my screenshot.
![screenshot from 2016-08-16 08 49 29](https://cloud.githubusercontent.com/assets/20678234/17690452/07b1e248-638f-11e6-9ffe-8c5c4eaf7c2c.png)

**Comment by colesbury** [comment]
The Data column is the time it takes for the data loader to return the next sample. That's why it's [reset at the end](https://github.com/facebook/fb.resnet.torch/blob/b7dbc816140816c403791ae83263a5df10a86dad/train.lua#L116) of a mini-batch and measured [immediately after the sample is returned](https://github.com/facebook/fb.resnet.torch/blob/b7dbc816140816c403791ae83263a5df10a86dad/train.lua#L98).

If the "Data" column large, then it means that you might be bottlenecked by loading images or by the image resizing & cropping. If you have a lot of CPUs/cores you should try increasing the number of data loading threads with `-nThreads` flag.

**Comment by albicasty** [comment]
ok, thank you!
