### ISSUE TITLE
Sampling batch instances by reverse class frequency in dataset, against imbalanced data

### ISSUE THREAD

**Issue by erogol** [facebook/fb.resnet.torch#96]
I like to implement sampling strategy against imbalanced data. For instance, if in a two classes case one class has 2x instances, I like to pick its instances by half of the probability of the other class. In that way, I like to equalize the batch population per class.

I am pretty new in Torch and like to hear some feedback to implement it in this code base. Thanks for any comment.

**Comment by colesbury** [comment]
The easiest way will be to change [ImagenetDataset:get(i)](https://github.com/facebook/fb.resnet.torch/blob/b7dbc816140816c403791ae83263a5df10a86dad/datasets/imagenet.lua#L28) to sample by class instead of returning the image at index `i`.

Something like:

1. `local class = torch.random(1, nClasses)`
2. `local imglist = imgslist[class]`
3. `local imgidx = imglist[torch.random(1, #imglist)]`

**Comment by erogol** [comment]
Thx I'll try :)
